"""create_customer_table

Revision ID: eff1132cafad
Revises: bcfe5d78373a
Create Date: 2025-05-21 14:26:01.021974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff1132cafad'
down_revision: Union[str, None] = 'bcfe5d78373a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('cpf', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_unique_constraint(None, 'customers', ['cpf'])
    op.create_unique_constraint(None, 'customers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_id'), table_name='customers')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_table('customers')
    # ### end Alembic commands ###
